version: 2
jobs:
# # # DO NOT TOUCH THIS AREAS, THIS FIXED CICD PROCESS # # #

# # # # # # 
# Dockerize 
# # On the master branch
  master:dockerize:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker # This step helps you avoid the Docker-in-Docker problem
      - run:
          name: Build Docker for Develop
          command: |
            export IMAGE_TAG=m-${CIRCLE_SHA1:0:8}
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY_HOST            
            docker build --target webapp -t ${IMAGE_REPOSITORY_WEBAPP}:${IMAGE_TAG} .
            docker build --target app -t ${IMAGE_REPOSITORY_API}:${IMAGE_TAG} .
            docker push ${IMAGE_REPOSITORY_WEBAPP}:${IMAGE_TAG}
            docker push ${IMAGE_REPOSITORY_API}:${IMAGE_TAG}

            
workflows:
  version: 2
  develop:
    jobs:
      - master:dockerize:
          filters:
            branches:
              only:
                - master
      